### PR TITLE
Finished page

### PR DESCRIPTION
**Pull request by SevlaMare**
Finished style, fixed margins, added thumbnail and Linter fix.

### CODE REVIEW

**Comment by SevlaMare** [comment]
fix all linter tips and w3c validator.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @SevlaMare and @JohannRodriguez 

### Good job on your first project :clap: However, you have a few changes to make for your project to be approved.

- Write a more detailed readme.md file, [follow this example](https://github.com/microverseinc/readme-template)
- Write a descriptive pull request stating what you have done on the project, [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- Add a sidebar with the thumbnail videos preview check [youtube for reference](https://www.youtube.com/watch?v=yYbLt-9oHpU)
sidebar

### Make these changes and resubmit for another coding review
- For assistance, contact me on @rOluochKe
- Happy coding

**Comment by SevlaMare** [comment]
@rOluochKe Thanks for your feedback, we fixed all appointments, and the new pull request is ready.

**Comment by kobiyoyo** [comment]
## Hi Team      
#### Great Job so far,as stated by the previous TSE a Descriptive Readme is mandatory.
### General
- [ ] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] please fix the horizontal scrolling .


 

### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
Request changes

**Comment by SevlaMare** [comment]
@kobiyoyo Hello Kobiyoyo, the horizontal scroll don't exits for wide screen monitor, since the layout not need to be responsible, if we fix it to a smaller screen, how much smaller should be?  The Readme file we fix on master branch (https://github.com/SevlaMare/youtube-clone), with screenshot and all.

**Comment by SevlaMare** [comment]
> Request changes
@kobiyoyo Hello Kobiyoyo, the horizontal scroll don't exits for wide screen monitor, since the layout not need to be responsible, if we fix it to a smaller screen, how much smaller should be? The Readme file we fix on master branch (https://github.com/SevlaMare/youtube-clone), with screenshot and all, because it's includes on gitignore.

**Comment by SevlaMare** [comment]
> ## Hi Team 
> #### Great Job so far,as stated by the previous TSE a Descriptive Readme is mandatory.
> ### General
> * [x]  The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> * [ ]  please fix the horizontal scrolling .
>   
> 
> ### Make changes and submit another code review request.
> _Happy coding_

@kobiyoyo Hello Kobiyoyo, the horizontal scroll don't exits for wide screen monitor, since the layout not need to be responsible, if we fix it to a smaller screen, how much smaller should be? The Readme file we fix on master branch (https://github.com/SevlaMare/youtube-clone), with screenshot and all, because it's includes on gitignore.

**Comment by pelzolga123** [comment]
## Hi Team!
### You did a good job so far! 
But there is one thing @rOluochKe asked for, that is still missing:
* [x] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by SevlaMare** [comment]
Finish style of page, fixed margins and added thumbnails.

**Pull request merged**
